### ISSUE TITLE
The script doesn't work - giving "Try Again Tomorrow", Its the first time I have used it.

### ISSUE THREAD

**Issue by lepras** [pishangujeniya/instagram-helper#98] opened 2023-05-08 08:43 UTC
I have followed the README and trying out un-send (A)

![insta-unsend](https://user-images.githubusercontent.com/109689648/236777990-ef148fdd-ad7c-4996-a720-0f6cb2adef1c.png)

In the same browser when i put the url `https://i.instagram.com/api/v1/direct_v2/threads/<id>/` in the address bar. I get this:

```
{"message":"useragent mismatch","status":"fail"}
```

Chrome Version Version 113.0.5672.64 (Official Build) (64-bit)

**Comment by pishangujeniya** [comment] 2023-05-08 10:04
Duplicate of https://github.com/pishangujeniya/instagram-helper/issues/95

**Closed** 2023-05-08 10:05 UTC
Labels: bug

**Comment by anashoussaini** [comment] 2023-06-02 02:09
any new updates regarding this?

**Comment by pishangujeniya** [comment] 2023-06-02 02:53
I am unable to reproduce so not fixed yet.
