### ISSUE TITLE
Error 404/Thread ID is too short.

### ISSUE THREAD

**Issue by Preppyprep** [pishangujeniya/instagram-helper#99] opened 2023-06-01 08:40 UTC
**Describe the bug**
I saw the two posts where it happened with someone else, and I still cannot find the solution. I want to use this script on THIS device. The thread ID is too short is what seems to be the problem after checking other posts out with the same error when downloading the message. 

**To Reproduce**
1. Go to 'Inspect Element'
2. Click on 'Console'
3. Enter the code, select B and copy/paste or manually put the thread ID.
4. Scroll down to 'The error'
5. See error

**Expected behavior**
I want it to start scraping the messages.

**Screenshots**
![image](https://github.com/pishangujeniya/instagram-helper/assets/69249209/2084221b-cea7-480e-8403-4de837130733)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Additional context**
I just want to use this on my device. I tried the networks thing, going to stuff in networks and checking out my thread ID there, maybe getting the longer one. And no. It had the same thread ID. I tried manually typing thread ID on the manual. It didn't work.

**Comment by pishangujeniya** [comment] 2023-06-01 08:43
duplicate of #95

**Closed by pishangujeniya** 2023-06-01 08:43 UTC
Labels: bug

**Comment by pishangujeniya** [comment] 2023-06-01 08:46
@Preppyprep  
Thanks for highlighting this issue, Even I am willing to fix it, But I can not re-produce the issue on my side. For me all the thread Ids are proper as previously it were. I have observed many people recently started facing this issue with shorter unusual thread Id but I am not having any such thread Id so that I can try to fix it.

I need to wait until I get that issue. Else if any other developer who is willing to fix it who have the same issue,  I appreciate that.

**Comment by Preppyprep** [comment] 2023-06-01 10:12
> Thanks for highlighting this issue #95 , Even I am willing to fix it, But I can not re-produce the issue on my side. For me all the thread Ids are proper as previously it were. I have observed many people recently started facing this issue with shorter unusual thread Id but I am not having any such thread Id so that I can try to fix it.

Let me know whatever information you need to diagnose this and I'll provide you. Do you maybe know a way to get the long thread ID, somehow?
