### ISSUE TITLE
Chat Thread ID 

### ISSUE THREAD

**Issue by idkasd1** [pishangujeniya/instagram-helper#97] opened 2023-05-06 15:41 UTC
![image](https://user-images.githubusercontent.com/132169758/236633722-3e7716a0-2f55-4569-bfd4-fd59d672128a.png)

Hey bro, 
I just made an new account and yea the thread id was too long not like mine on my main account
I tested the tool and it works 100%

So What can i do to make my id thread long like this... I think at first time it was long then it shorted without any reason
even when i copy and paste it , it not change to hash 
when u copy the long id it auto change to hash like this
6361235215 >>>  656xzczrXdsafsacx2

but mine not change or something its short one 

I tried to signout and login again nothing change same chat id

so if u have any idea tell me

**Comment by pishangujeniya** [comment] 2023-05-08 10:03
Duplicate of https://github.com/pishangujeniya/instagram-helper/issues/95

**Comment by pishangujeniya** [comment] 2023-05-08 10:07
@idkasd1  Will be fixed with https://github.com/pishangujeniya/instagram-helper/issues/95

**Closed by pishangujeniya** 2023-05-08 10:07 UTC
Labels: bug

**Comment by idkasd1** [comment] 2023-05-08 21:48
thanks dude im waiting 
![image](https://user-images.githubusercontent.com/132169758/236944047-a10542bd-5f8b-4bde-a7ea-f0155c9dc6b3.png)
